-- MySQL Script generated by MySQL Workbench
-- Fri Aug 14 17:39:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sans_merise
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sans_merise
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sans_merise` DEFAULT CHARACTER SET utf8 ;
USE `sans_merise`;

-- -----------------------------------------------------
-- Table `sans_merise`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`users` (
  `users_id` INT NOT NULL AUTO_INCREMENT,
  `users_lastname` VARCHAR(70) NULL,
  `users_firstname` VARCHAR(70) NULL,
  `users_birthdate` DATE NULL,
  `users_mail` VARCHAR(255) NULL,
  `users_password` VARCHAR(60) NULL,
  `users_phone` VARCHAR(20) NULL,
  `users_cgu` INT NULL,
  PRIMARY KEY (`users_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sans_merise`.`dirtywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`dirtywords` (
  `dirtywords_id` INT NOT NULL AUTO_INCREMENT,
  `dirtywords_languages` VARCHAR(20) NULL,
  `dirtywords_word` VARCHAR(20) NULL,
  PRIMARY KEY (`dirtywords_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sans_merise`.`movies_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`movies_messages` (
  `movies_messages_id` INT NOT NULL AUTO_INCREMENT,
  `movies_messages_name` VARCHAR(150) NULL,
  PRIMARY KEY (`movies_messages_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sans_merise`.`pictures_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`pictures_messages` (
  `pictures_messages_id` INT NOT NULL AUTO_INCREMENT,
  `picture_messages_name` VARCHAR(150) NULL,
  PRIMARY KEY (`pictures_messages_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sans_merise`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`messages` (
  `messages_id` INT NOT NULL AUTO_INCREMENT,
  `messages_content` LONGTEXT NULL,
  `dirtywords_dirtywords_id` INT NOT NULL,
  `movies_messages_id` INT NOT NULL,
  `pictures_messages_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`messages_id`),
  CONSTRAINT `fk_messages_dirtywords1`
    FOREIGN KEY (`dirtywords_dirtywords_id`)
    REFERENCES `sans_merise`.`dirtywords` (`dirtywords_id`),
  CONSTRAINT `fk_messages_movies_messages`
    FOREIGN KEY (`movies_messages_id`)
    REFERENCES `sans_merise`.`movies_messages` (`movies_messages_id`),
  CONSTRAINT `fk_messages_pictures_messages1`
    FOREIGN KEY (`pictures_messages_id`)
    REFERENCES `sans_merise`.`pictures_messages` (`pictures_messages_id`),
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`users_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sans_merise`.`zipcode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`zipcode` (
  `zipcode_id` INT NOT NULL AUTO_INCREMENT,
  `zipcode_number` VARCHAR(10) NULL,
  PRIMARY KEY (`zipcode_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sans_merise`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`country` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(255) NULL,
  `zipcode_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`country_id`),
  CONSTRAINT `fk_country_zipcode1` FOREIGN KEY (`zipcode_id`) REFERENCES `sans_merise`.`zipcode` (`zipcode_id`),
  CONSTRAINT `fk_country_users1`FOREIGN KEY (`users_id`) REFERENCES `sans_merise`.`users` (`users_id`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `sans_merise`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`events` (
  `events_id` INT NOT NULL AUTO_INCREMENT,
  `events_name` VARCHAR(150) NULL,
  `events_content` LONGTEXT NULL,
  `events_date` DATE NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`events_id`),
  CONSTRAINT `fk_events_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `sans_merise`.`users` (`users_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sans_merise`.`elements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`elements` (
  `elements_id` INT NOT NULL AUTO_INCREMENT,
  `elements_content` LONGTEXT NULL,
  PRIMARY KEY (`elements_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sans_merise`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`comments` (
  `comments_id` INT NOT NULL AUTO_INCREMENT,
  `comments_content` LONGTEXT NULL,
  `dirtywords_id` INT NOT NULL,
  PRIMARY KEY (`comments_id`),
  CONSTRAINT `fk_comments_dirtywords1`
    FOREIGN KEY (`dirtywords_id`)
    REFERENCES `sans_merise`.`dirtywords` (`dirtywords_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `sans_merise`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`albums` (
  `albums_id` INT NOT NULL AUTO_INCREMENT,
  `albums_name` VARCHAR(255) NULL,
  `albums_content` VARCHAR(255) NULL,
  PRIMARY KEY (`albums_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sans_merise`.`movies_posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`movies_posts` (
  `movies_posts_id` INT NOT NULL AUTO_INCREMENT,
  `movies_posts_name` VARCHAR(45) NULL,
  `albums_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`movies_posts_id`),
  CONSTRAINT `fk_movies_posts_albums1`
    FOREIGN KEY (`albums_id`)
    REFERENCES `sans_merise`.`albums` (`albums_id`),
  CONSTRAINT `fk_movies_posts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `sans_merise`.`users` (`users_id`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `sans_merise`.`pictures_posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`pictures_posts` (
  `pictures_posts_id` INT NOT NULL AUTO_INCREMENT,
  `pictures_posts_name` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  `albums_id` INT NOT NULL,
  PRIMARY KEY (`pictures_posts_id`),
  CONSTRAINT `fk_pictures_posts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `sans_merise`.`users` (`users_id`),
  CONSTRAINT `fk_pictures_posts_albums1`
    FOREIGN KEY (`albums_id`)
    REFERENCES `sans_merise`.`albums` (`albums_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sans_merise`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`notes` (
  `notes_id` INT NOT NULL AUTO_INCREMENT,
  `notes_value` INT NULL,
  PRIMARY KEY (`notes_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sans_merise`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`posts` (
  `posts_id` INT NOT NULL AUTO_INCREMENT,
  `posts_content` LONGTEXT NULL,
  `elements_id` INT NOT NULL,
  `movies_posts_id` INT NOT NULL,
  `pictures_posts_id` INT NOT NULL,
  `dirtywords_id` INT NOT NULL,
  `comments_id` INT NOT NULL,
  `notes_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`posts_id`),
  CONSTRAINT `fk_posts_elements1`
    FOREIGN KEY (`elements_id`)
    REFERENCES `sans_merise`.`elements` (`elements_id`),
  CONSTRAINT `fk_posts_movies_posts1`
    FOREIGN KEY (`movies_posts_id`)
    REFERENCES `sans_merise`.`movies_posts` (`movies_posts_id`),
  CONSTRAINT `fk_posts_pictures_posts1`
    FOREIGN KEY (`pictures_posts_id`)
    REFERENCES `sans_merise`.`pictures_posts` (`pictures_posts_id`),
  CONSTRAINT `fk_posts_dirtywords1`
    FOREIGN KEY (`dirtywords_id`)
    REFERENCES `sans_merise`.`dirtywords` (`dirtywords_id`),
  CONSTRAINT `fk_posts_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `sans_merise`.`comments` (`comments_id`),
  CONSTRAINT `fk_posts_notes1`
    FOREIGN KEY (`notes_id`)
    REFERENCES `sans_merise`.`notes` (`notes_id`),
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `sans_merise`.`users` (`users_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sans_merise`.`genreds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`genreds` (
  `genders_id` INT NOT NULL AUTO_INCREMENT,
  `genreds_value` INT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`genders_id`),
  CONSTRAINT `fk_genreds_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `sans_merise`.`users` (`users_id`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `sans_merise`.`add_friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`add_friends` (
  `add_friends_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`add_friends_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sans_merise`.`profil_pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`profil_pictures` (
  `profil_pictures_id` INT NOT NULL AUTO_INCREMENT,
  `profil_pictures_img` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`profil_pictures_id`),
  CONSTRAINT `fk_profil_pictures_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `sans_merise`.`users` (`users_id`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `sans_merise`.`notifys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`notifys` (
  `notifys_id` INT NOT NULL AUTO_INCREMENT,
  `notifys_content` LONGTEXT NULL,
  `posts_id` INT NOT NULL,
  `comments_id` INT NOT NULL,
  PRIMARY KEY (`notifys_id`),
  CONSTRAINT `fk_notifys_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `sans_merise`.`posts` (`posts_id`),
  CONSTRAINT `fk_notifys_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `sans_merise`.`comments` (`comments_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sans_merise`.`add_friends_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sans_merise`.`add_friends_has_users` (
  `add_friends_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`add_friends_add_friends_id`, `users_users_id`),
  CONSTRAINT `fk_add_friends_has_users_add_friends1`
    FOREIGN KEY (`add_friends_id`)
    REFERENCES `sans_merise`.`add_friends` (`add_friends_id`),
  CONSTRAINT `fk_add_friends_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `sans_merise`.`users` (`users_id`))
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;