-- MySQL Script generated by MySQL Workbench
-- Sat Aug 22 17:20:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema spacebrico
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema spacebrico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spacebrico` DEFAULT CHARACTER SET utf8 ;
USE `spacebrico` ;
-- -----------------------------------------------------
-- Table `spacebrico`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spacebrico`.`city` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(45) NULL,
  `city_zipcode` VARCHAR(45) NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `spacebrico`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spacebrico`.`users` (
  `users_id` INT NOT NULL AUTO_INCREMENT,
  `users_lastname` VARCHAR(70) NULL,
  `users_firstname` VARCHAR(70) NULL,
  `users_birthdate` DATE NULL,
  `users_mail` VARCHAR(255) NULL,
  `users_password` VARCHAR(60) NULL,
  `users_phone` VARCHAR(20) NULL,
  `users_cgu` INT NULL,
  `profil_pictures` VARCHAR(45) NULL,
  `gender` INT NULL,
  `grads` VARCHAR(45) NULL,
  `fk_city_id` INT NOT NULL,
  PRIMARY KEY (`users_id`),
  CONSTRAINT `fk_users_city1`
    FOREIGN KEY (`fk_city_id`)
    REFERENCES `spacebrico`.`city` (`city_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `spacebrico`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spacebrico`.`messages` (
  `messages_id` INT NOT NULL AUTO_INCREMENT,
  `messages_content` LONGTEXT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`messages_id`),
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `spacebrico`.`users` (`users_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `spacebrico`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spacebrico`.`events` (
  `events_id` INT NOT NULL AUTO_INCREMENT,
  `events_name` VARCHAR(150) NULL,
  `events_content` LONGTEXT NULL,
  `events_date` DATE NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`events_id`),
  CONSTRAINT `fk_events_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `spacebrico`.`users` (`users_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `spacebrico`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spacebrico`.`posts` (
  `posts_id` INT NOT NULL AUTO_INCREMENT,
  `posts_content` LONGTEXT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`posts_id`),
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `spacebrico`.`users` (`users_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `spacebrico`.`elements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spacebrico`.`elements` (
  `elements_id` INT NOT NULL AUTO_INCREMENT,
  `elements_content` LONGTEXT NULL,
  `posts_id` INT NOT NULL,
  PRIMARY KEY (`elements_id`),
  CONSTRAINT `fk_elements_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `spacebrico`.`posts` (`posts_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `spacebrico`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spacebrico`.`comments` (
  `comments_id` INT NOT NULL AUTO_INCREMENT,
  `comments_content` LONGTEXT NULL,
  `posts_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`comments_id`),
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `spacebrico`.`posts` (`posts_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `spacebrico`.`users` (`users_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `spacebrico`.`dirtywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spacebrico`.`dirtywords` (
  `dirtywords_id` INT NOT NULL AUTO_INCREMENT,
  `dirtywords_languages` VARCHAR(20) NULL,
  `dirtywords_word` VARCHAR(20) NULL,
  `comments_comments_id` INT NOT NULL,
  `messages_id` INT NOT NULL,
  `posts_posts_id` INT NOT NULL,
  `elements_id` INT NOT NULL,
  PRIMARY KEY (`dirtywords_id`),
  CONSTRAINT `fk_dirtywords_comments1`
    FOREIGN KEY (`comments_comments_id`)
    REFERENCES `spacebrico`.`comments` (`comments_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_dirtywords_messages1`
    FOREIGN KEY (`messages_id`)
    REFERENCES `spacebrico`.`messages` (`messages_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_dirtywords_posts1`
    FOREIGN KEY (`posts_posts_id`)
    REFERENCES `spacebrico`.`posts` (`posts_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_dirtywords_elements1`
    FOREIGN KEY (`elements_id`)
    REFERENCES `spacebrico`.`elements` (`elements_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `spacebrico`.`pictures_posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spacebrico`.`pictures_posts` (
  `pictures_posts_id` INT NOT NULL AUTO_INCREMENT,
  `pictures_posts_name` VARCHAR(45) NULL,
  `posts_id` INT NOT NULL,
  PRIMARY KEY (`pictures_posts_id`),
  CONSTRAINT `fk_pictures_posts_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `spacebrico`.`posts` (`posts_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `spacebrico`.`movies_posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spacebrico`.`movies_posts` (
  `movies_posts_id` INT NOT NULL AUTO_INCREMENT,
  `movies_posts_name` VARCHAR(45) NULL,
  `posts_id` INT NOT NULL,
  PRIMARY KEY (`movies_posts_id`),
  CONSTRAINT `fk_movies_posts_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `spacebrico`.`posts` (`posts_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `spacebrico`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spacebrico`.`albums` (
  `albums_id` INT NOT NULL AUTO_INCREMENT,
  `albums_name` VARCHAR(255) NULL,
  `albums_content` VARCHAR(255) NULL,
  `posts_id` INT NOT NULL,
  PRIMARY KEY (`albums_id`),
  CONSTRAINT `fk_albums_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `spacebrico`.`posts` (`posts_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `spacebrico`.`add_friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spacebrico`.`add_friends` (
  `add_friends_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`add_friends_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `spacebrico`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spacebrico`.`notes` (
  `notes_id` INT NOT NULL AUTO_INCREMENT,
  `notes_value` INT NULL,
  `posts_id` INT NOT NULL,
  PRIMARY KEY (`notes_id`),
  CONSTRAINT `fk_notes_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `spacebrico`.`posts` (`posts_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `spacebrico`.`notifys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spacebrico`.`notifys` (
  `notifys_id` INT NOT NULL AUTO_INCREMENT,
  `posts_id` INT NOT NULL,
  `comments_id` INT NOT NULL,
  PRIMARY KEY (`notifys_id`),
  CONSTRAINT `fk_notifys_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `spacebrico`.`posts` (`posts_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_notifys_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `spacebrico`.`comments` (`comments_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `spacebrico`.`movies_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spacebrico`.`movies_messages` (
  `movies_messages_id` INT NOT NULL AUTO_INCREMENT,
  `movies_messages_name` VARCHAR(150) NULL,
  `messages_id` INT NOT NULL,
  PRIMARY KEY (`movies_messages_id`),
  CONSTRAINT `fk_movies_messages_messages1`
    FOREIGN KEY (`messages_id`)
    REFERENCES `spacebrico`.`messages` (`messages_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `spacebrico`.`pictures_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spacebrico`.`pictures_messages` (
  `pictures_messages_id` INT NOT NULL AUTO_INCREMENT,
  `picture_messages_name` VARCHAR(150) NULL,
  `messages_id` INT NOT NULL,
  PRIMARY KEY (`pictures_messages_id`),
  CONSTRAINT `fk_pictures_messages_messages1`
    FOREIGN KEY (`messages_id`)
    REFERENCES `spacebrico`.`messages` (`messages_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `spacebrico`.`users_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spacebrico`.`users_has_users` (
  `users_id` INT NOT NULL,
  `users_id_friends` INT NOT NULL,
  PRIMARY KEY (`users_id`, `users_id_friends`),
  CONSTRAINT `fk_users_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `spacebrico`.`users` (`users_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_users_has_users_users2`
    FOREIGN KEY (`users_id_friends`)
    REFERENCES `spacebrico`.`users` (`users_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
-- -----------------------------------------------------
-- Table `spacebrico`.`events_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spacebrico`.`events_has_users` (
  `e_events_id` INT NOT NULL,
  `e_users_id` INT NOT NULL,
  PRIMARY KEY (`e_events_id`, `e_users_id`),
  CONSTRAINT `fk_events_has_users_events1`
    FOREIGN KEY (`e_events_id`)
    REFERENCES `spacebrico`.`events` (`events_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_events_has_users_users1`
    FOREIGN KEY (`e_users_id`)
    REFERENCES `spacebrico`.`users` (`users_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
